-- membuat database
CREATE DATABASE IF NOT EXISTS bookbank;
USE bookbank;

-- membuat table buku
CREATE TABLE list_data_buku (
    Id VARCHAR(3),
    Genre VARCHAR(25),
    Judul VARCHAR(512),
    Penulis VARCHAR(512),
    Penerbit VARCHAR(512),
    Tahun_Terbit VARCHAR(512),
    ISBN VARCHAR(512),
    Sinopsis text,
    Link VARCHAR(512)
);

-- memasukan data buku
INSERT INTO list_data_buku (Id, Genre, Judul, Penulis, Penerbit, Tahun_Terbit, ISBN, Sinopsis, Link) VALUES
('1', 'Biografi', 'Kisah, perjuangan, & inspirasi B.J. Habibie', 'Weda S. Atma', 'Checklist Media', 'Oktober 2017', '978-602-6763-96-9', 'Buku Kisah, Perjuangan & Inspirasi B.J. Habibie karya Weda S. Atma menceritakan kisah di balik kesuksesan Prof. Dr. Ing. H. Bachruddin Jusuf Habibie, yang dikenal sebagai Bapak Teknologi Indonesia. Biografi ini mengungkap kecerdasan dan kecemerlangan Habibie dalam menuntut ilmu serta kariernya sebagai tokoh politik yang menginspirasi banyak orang. Buku ini juga mengisahkan masa kecil, remaja, serta kiprah Habibie dalam dunia politik, termasuk kehidupan romantisnya bersama Ainun Habibie. Perjuangan dan kegigihan Habibie dari masa ke masa menjadi fokus utama buku ini, dengan tujuan menyebarkan semangat dan optimisme dalam belajar, meniti karier, serta menaklukkan tantangan.', 'https://www.gramedia.com/products/bj-habibie-kisah-perjuangan-inspirasi'),

('2', 'Biografi', 'Mohammad Hatta: Biografi Singkat 1902-1980', 'Salman Alfarizi', 'Garasi House of Book', 'Januari 2009', '978-623-7219-63-7', 'Buku Mohammad Hatta: Biografi Singkat 1902-1980 karya Salman Alfarizi adalah sebuah karya yang menggambarkan kehidupan dan perjuangan Mohammad Hatta, salah satu tokoh pendiri Indonesia. Biografi ini memaparkan perjalanan Hatta dari lahir pada tahun 1902 hingga meninggal pada tahun 1980. Buku ini membahas berbagai aspek kehidupan Hatta, termasuk latar belakang keluarganya, pendidikan, peran dalam pergerakan kemerdekaan Indonesia, serta kontribusinya sebagai wakil presiden pertama Indonesia. Selain itu, biografi ini juga mengulas perannya dalam pembentukan kebijakan ekonomi dan politik negara serta pengabdian Hatta dalam menjalankan tugas-tugasnya sebagai seorang pemimpin dan negarawan. Dengan gaya penulisan yang ringkas namun informatif, buku ini memberikan wawasan yang mendalam tentang kehidupan dan karya Mohammad Hatta sebagai salah satu tokoh sentral dalam sejarah Indonesia.', 'https://www.goodreads.com/book/show/20808645-mohammad-hatta?ac=1&from_search=true&qid=zjAE0GB8ke&rank=1'),

('3', 'Biografi', 'Buya Hamka: Sebuah Novel Biografi', 'Haidar Musyafa', 'IIMan', 'Januari 2018', '978-602-7926-39-4', 'Buku biografi berjudul Hamka mengisahkan perjalanan hidup Malik, yang kemudian dikenal sebagai Buya Hamka. Dilahirkan di kampung seberang Danau Maninjau pada 17 Februari 1908, Malik berasal dari keluarga yang terlibat dalam Sumatera Thawalib, sebuah sekolah keagamaan terkemuka pada masa pra-kemerdekaan. Meskipun awalnya bandel dan kurang tertarik pada pendidikan formal, ia memiliki semangat yang kuat untuk belajar. Perjalanan hidupnya membawanya ke Jogja dan kemudian ke Makkah, di mana ia menetap dan menemukan panggilan dalam menulis dan berdakwah. Karya utamanya, Tenggelamnya Kapal Van Der Wijk, membuatnya dikenal luas. Buku ini menggabungkan elemen biografi dengan karakteristik novel, dengan bahasa yang mudah dipahami dan alur cerita yang menarik, meskipun dengan beberapa kelebihan dalam penggunaan hiperbola. Meski demikian, buku ini sangat baik bagi pembaca yang ingin mengetahui lebih banyak tentang Buya Hamka.', 'https://www.goodreads.com/book/show/39904483-buya-hamka?ref=nav_sb_ss_1_33'),

('4', 'Biografi', 'Bob Sadino: Pikiran, Tindakan, dan Pesan Pesan Bisnis Anti Mainstream', 'Alam Bachtiar', 'Araska', 'Juli 2022', '978-623-7910-38-1', 'Buku Bob Sadino karya Alam Bachtiar menguraikan kisah hidup dan perjalanan bisnis Bob Sadino, seorang tokoh sukses di dunia bisnis yang dikenal dengan pemikiran dan ide-idenya yang anti mainstream. Buku ini menekankan pentingnya keseriusan dan semangat pantang menyerah dalam menekuni bisnis, serta belajar dari para pebisnis sukses seperti Bob Sadino. Bob Sadino percaya bahwa kesuksesan tidak datang secara instan dan selalu melibatkan kesulitan dan kegagalan. Buku ini mengungkap konsep dasar kesuksesan Bob Sadino yang dikenal sebagai 4 kuadran kesuksesan: tahu, bisa, terampil, dan ahli, yang menentukan tingkat kesuksesan seorang pebisnis. Selain itu, Sadino menekankan pentingnya tindakan nyata dalam menjalankan bisnis, dengan mengkritik orang yang bersemangat membicarakan ide tanpa merealisasikannya, digambarkan sebagai nafsu kuda, tapi tenaga ayam. Buku ini menjadi sumber motivasi bagi para pebisnis untuk berani berpikir cerdas dan bertindak nyata dalam mencapai kesuksesan.', 'https://www.gramedia.com/products/bob-sadino-pikiran-tindakan-dan-pesan-pesan-bisnis'),

('5', 'Biografi', 'Einstein : kehidupan dan pengaruhnya bagi dunia', 'Walter Isaacson', 'Bentang Pustaka', 'Januari 2012', '978-623-186-215-0', 'Rasa ingin tahu adalah awal yang baik, namun rasa ingin tahu saja sudah terlalu sederhana untuk dijawab. Einstein memiliki cara berpikir yang sangat berbeda. Dia akan mempertanyakan teori-teori yang sudah mapan dan fenomena yang tampaknya biasa. Dia tidak mengenali eter sebagai sebuah konsep yang tidak dapat dideteksi atau diberi makna fisik apa pun. Dia melihat persamaan percepatan dan gravitasi, dan menggunakannya untuk memahami gagasan berkas cahaya melengkung. Einstein mampu melihat realitas fisik dalam rumus matematika abstrak dan percaya bahwa alam cenderung sederhana dan indah. Dia menganggap musik Beethoven kreatif, Wagner dekaden, dan Bach serta Mozart sederhana dan jelas, mencerminkan keyakinannya bahwa alam merealisasikan ide-ide matematika yang paling sederhana. Upayanya untuk menyatukan mekanika Newton, elektromagnetisme Maxwell, dan mekanika kuantum ke dalam teori medan terpadu menunjukkan keinginannya akan kesatuan. Keyakinan politiknya juga mencerminkan keinginannya untuk persatuan, namun tanpa mengorbankan kebebasan pribadi. Dia menolak segala bentuk tirani, termasuk Nazisme, Stalinisme, dan McCarthyisme, dan menganggap kebebasan sebagai sumber semua kreativitas. Einstein percaya pada Tuhan Spinozan yang mengungkapkan dirinya dalam harmoni alam, dan bukan Tuhan pribadi yang campur tangan dalam kehidupan sehari-hari. Sebagai seorang determinis, dia menolak keacakan mekanika kuantum dan tidak percaya pada kehendak bebas, tetapi tetap mengembangkan moralitas praktis yang mendorong tanggung jawab dan kemurahan hati. Saat mengunjungi Jepang pada tahun 1922, ia menasihati keluarganya untuk hidup bermoral dengan memberikan banyak kepada orang lain.', 'https://www.goodreads.com/book/show/16157744-einstein?ref=nav_sb_ss_1_47'),

('6', 'Biografi', 'Biografi Saddam Hussein : inspirasi perlawanan terhadap Amerika Serikat', 'Zaenal Arifin', 'Narasi', 'Juli 2007', '979-168-046-9', 'Joseph Wilson, diplomat AS yang pernah bertugas di Baghdad (1988-1991), menyebutnya sebagai “seorang sociopath”. Sementara Rashid Khalidi, Direktur Middle East Institute di Columbia University, memanggilnya “megalomania yang kejam”. Tokoh yang oleh presiden AS George W. Bush dijuluki “musang gurun” ini, juga menyebutnya sebagai penjahat perang paling biadab yang masih hidup saat itu. Biografi Saddam Hussein memang penuh warna dan kontroversial. Saddam Hussein lahir di desa Al-Auja, di tepi sungai Tigris, Tikrit, 28 April 1937. Lahir sebagai yatim piatu, besar dalam asuhan paman dari pihak ibu yang kelak membentuk karakternya menjadi pejuang penuh dendam. Saddam adalah gambaran klasik seorang revolusioner yang berdiri dalam kemiskinan dan ketertindasan. Sejak 1957, Saddam telah aktif dalam berbagai kegiatan politik menentang penguasa Irak saat itu, Raja Faisal II, hingga menjadi target pembunuhan oleh rezim tersebut. Biografi ini mengungkapkan bagaimana Saddam, sebagai seorang revolusioner yang terinspirasi oleh perjuangan kerasnya dari kecil, menjelma menjadi pemimpin yang kejam dan ambisius. Saddam Hussein tak hanya menjadi tokoh sentral dalam sejarah modern Irak, namun juga menjadi simbol perlawanan terhadap dominasi asing, khususnya Amerika Serikat. Buku ini mengajak pembaca untuk memahami kompleksitas kehidupan dan perjuangan Saddam Hussein, dari masa kecil yang penuh penderitaan hingga menjadi penguasa Irak yang kontroversial.', 'https://www.goodreads.com/book/show/6694404-biografi-saddam-hussein?from_search=true&from_srp=true&qid=bz8scyIBHl&rank=3'),

('7', 'Biografi', 'Nelson Mandela: The Life of an Icon', 'Anthony Sampson', 'HarperCollins', '2000', '978-0-06-178766-5', 'Buku ini memberikan pandangan mendalam tentang kehidupan Nelson Mandela, mulai dari masa kecilnya di sebuah desa kecil di Afrika Selatan hingga menjadi simbol perjuangan melawan apartheid. Anthony Sampson, yang telah mengenal Mandela selama lebih dari empat puluh tahun, memberikan wawasan yang mendalam tentang pemimpin yang kharismatik ini, menyoroti keberanian, integritas, dan pengorbanan yang dilakukannya demi keadilan dan kebebasan. Buku ini juga mengeksplorasi kehidupan pribadi Mandela, termasuk hubungan dan tantangan yang dihadapinya selama bertahun-tahun dalam penjara. Ini adalah potret yang menginspirasi dari seorang pria yang luar biasa dan dampaknya terhadap dunia.', 'https://www.goodreads.com/book/show/11776.Mandela'),

('8', 'Biografi', 'Steve Jobs: The Geek Mastermind', 'Ibrahim Nubika', 'Alpha Books', 'April 2018', '978-602-03-8824-7', 'Buku ini menggambarkan kisah inspiratif Steve Jobs, pendiri Apple Inc., yang dikenal sebagai salah satu inovator teknologi paling berpengaruh di dunia. Steve Jobs: The Geek Mastermind mengupas perjalanan hidup Jobs dari masa kecilnya, pendidikan, hingga kesuksesan dalam menciptakan produk-produk revolusioner seperti iPhone, iPad, dan Mac. Ibrahim Nubika menceritakan bagaimana Jobs, dengan visi dan kegigihannya, mampu mengubah wajah industri teknologi dan menginspirasi jutaan orang di seluruh dunia. Buku ini juga mengeksplorasi sisi personal Jobs, termasuk tantangan dan kontroversi yang dihadapinya sepanjang kariernya. Dengan gaya penulisan yang menarik dan informatif, buku ini menjadi bacaan wajib bagi siapa saja yang ingin mengetahui lebih banyak tentang tokoh yang telah mengubah dunia ini.', 'https://www.gramedia.com/products/steve-jobs-the-geek-mastermind'),

('9', 'Biografi', 'Imam Syafii: The Architect of Islamic Jurisprudence', 'Tariq Suwaidan', 'Al-Wafi Publishing', 'Mei 2015', '978-9953-82-496-4', 'Buku ini mengupas kehidupan dan karya Imam Syafii, salah satu tokoh terkemuka dalam sejarah Islam yang dikenal sebagai pendiri salah satu mazhab fiqh terbesar. Dr. Tariq Suwaidan menjelaskan latar belakang sejarah dan intelektual Imam Syafii, serta kontribusinya dalam mengembangkan ilmu hukum Islam. Buku ini juga menyoroti pemikiran dan metode ijtihad Imam Syafii, serta bagaimana karyanya telah mempengaruhi dunia Islam hingga hari ini. Dengan penulisan yang mendalam dan analitis, buku ini menjadi sumber referensi penting bagi siapa saja yang ingin memahami lebih dalam tentang tokoh besar ini dan warisannya dalam bidang hukum Islam.', 'https://www.goodreads.com/book/show/25813758-imam-shafii?ac=1&from_search=true&qid=7zA3zOqRhb&rank=1'),

('10', 'Biografi', 'Jalan Tengah Demokrasi: Antara Fundamentalisme dan Sekularisme', 'Tohir Bawazir', 'Pustaka Al-Kautsar', '2019', '978-979-592-895-2', 'Buku ini membahas tantangan dan dinamika demokrasi di Indonesia, khususnya dalam konteks perdebatan antara fundamentalisme dan sekularisme. Tohir Bawazir menguraikan bagaimana demokrasi di Indonesia dapat berkembang dengan mengambil jalan tengah yang mengakomodasi nilai-nilai keagamaan dan modernitas. Buku ini juga mengeksplorasi peran Islam dalam politik Indonesia dan bagaimana prinsip-prinsip demokrasi dapat diterapkan dalam kerangka yang sesuai dengan budaya dan nilai-nilai lokal. Dengan analisis yang mendalam dan contoh kasus yang relevan, buku ini menjadi bacaan penting bagi siapa saja yang tertarik pada studi politik dan demokrasi di Indonesia.', 'https://www.goodreads.com/book/show/44399457-jalan-tengah-demokrasi?ac=1&from_search=true&qid=6cW74OedPo&rank=1'),

('10', 'Biografi', 'Steve Jobs : The Geek Mastermind', 'Ibrahim Nubika', 'Anak Indonesia Hebat', 'September 2021', '978-623-244-636-6', 'Buku Steve Jobs: The Geek Mastermind karya Ibrahim Nubika mengisahkan perjalanan hidup Steve Jobs, pendiri Apple Inc., yang dikenal sebagai salah satu inovator paling berpengaruh di dunia teknologi. Buku ini menguraikan masa kecil Jobs, termasuk adopsinya oleh keluarga Jobs, masa remajanya yang penuh dengan eksplorasi, dan awal mula ketertarikannya pada teknologi dan desain. Cerita berlanjut dengan pendirian Apple bersama Steve Wozniak, serta perjuangan mereka mengembangkan komputer pribadi pertama. Buku ini juga membahas berbagai produk revolusioner yang diciptakan di bawah kepemimpinan Jobs, seperti Macintosh, iPod, iPhone, dan iPad, yang mengubah industri teknologi dan gaya hidup masyarakat global. Selain kesuksesannya, buku ini mengungkap sisi pribadi Jobs, termasuk tantangan yang dihadapinya, seperti pemecatan dari Apple, perjuangannya melawan penyakit, serta kembalinya ke Apple dan memimpin perusahaan menuju kejayaan baru. Steve Jobs: The Geek Mastermind juga menyoroti filosofi Jobs tentang inovasi, desain, dan pentingnya menggabungkan seni dengan teknologi.', 'https://www.gramedia.com/products/steve-jobs-the-geek-mastermind'),

('11', 'Non Fiksi', 'Jalan Tengah Demokrasi: Antara Fundamentalisme dan Sekularisme', 'Tohir Bawazir', 'Pustaka Al-Kautsar', 'Juli 2015', '978-979-592-707-5', 'Buku Jalan Tengah Demokrasi: Antara Fundamentalisme dan Sekularisme karya Tohir Bawazir mengeksplorasi konsep demokrasi yang seimbang antara fundamentalisme agama dan sekularisme. Bawazir berpendapat bahwa demokrasi tidak harus ekstrem di salah satu ujung spektrum, tetapi dapat menemukan jalan tengah yang memadukan nilai-nilai religius dengan prinsip-prinsip sekuler. Dia menganalisis tantangan dan potensi konflik yang muncul dari fundamentalisme yang berusaha menerapkan hukum agama secara kaku dalam pemerintahan, serta sekularisme yang cenderung memisahkan agama sepenuhnya dari ranah publik. Buku ini menawarkan solusi untuk mencapai harmonisasi antara kedua kutub tersebut, dengan menekankan pentingnya dialog, toleransi, dan penghormatan terhadap pluralisme dalam masyarakat demokratis. Bawazir juga menyoroti pengalaman berbagai negara dalam mengimplementasikan demokrasi yang inklusif dan berimbang, serta memberikan rekomendasi praktis untuk mencapainya. Buku ini penting bagi para pembaca yang tertarik pada isu-isu demokrasi, kebebasan beragama, dan hubungan antara agama dan negara.', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=1195227'),

('12', 'Non Fiksi', 'Literasi politik : dinamika konsolidasi demokrasi Indonesia pascareformasi', 'Gun Gun Heryanto', 'CV. IRCiSOD', 'Juli 2019', '978-602-7696-89-1', 'Buku Literasi Politik: Dinamika Konsolidasi Demokrasi Indonesia Pascareformasi karya Gun Gun Heryanto membahas perkembangan dan tantangan demokrasi di Indonesia setelah era reformasi. Buku ini mengulas bagaimana literasi politik masyarakat Indonesia mempengaruhi konsolidasi demokrasi, serta peran berbagai aktor politik dalam proses tersebut. Penulis menyoroti pergeseran dinamika politik, peningkatan partisipasi politik masyarakat, dan tantangan yang dihadapi dalam menjaga stabilitas demokrasi. Selain itu, buku ini membahas pentingnya pendidikan politik dan media dalam membentuk kesadaran politik masyarakat. Gun Gun Heryanto juga mengkritisi praktik politik yang belum sepenuhnya demokratis dan mengajukan rekomendasi untuk memperkuat literasi politik guna mendukung konsolidasi demokrasi yang lebih baik di Indonesia.', 'https://www.goodreads.com/book/show/58905967-literasi-politik?ref=nav_sb_ss_1_74'),

('13', 'Non Fiksi', 'Nalar Kritis Pendidikan', 'Arfan Muammar', 'CV. IRCiSOD', 'Desember 2019', '978-623-7378-03-7', 'Buku Nalar Kritis Pendidikan karya Arfan Muammar membahas berbagai aspek pendidikan secara mendalam dan kritis. Penulis mengajak pembaca untuk mempertimbangkan berbagai tantangan dan masalah dalam dunia pendidikan, serta memberikan sudut pandang yang kritis terhadap isu-isu tersebut. Buku ini menawarkan analisis tentang kondisi pendidikan saat ini, tantangan-tantangan yang dihadapi, dan berbagai upaya pemecahan masalah yang dapat dilakukan. Arfan Muammar membahas pentingnya nalar kritis dalam meningkatkan kualitas pendidikan, baik dari segi akademis maupun karakter. Selain itu, buku ini juga mengupas berbagai teori dan konsep pendidikan kontemporer yang relevan, serta mengaitkannya dengan realitas pendidikan di Indonesia. Penulis menyoroti peran guru, kurikulum, teknologi, dan kebijakan pendidikan dalam membentuk masa depan pendidikan yang lebih baik.', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=1240783'),

('14', 'Non Fiksi', 'Madilog', 'Tan Malaka', 'CV. IRCiSOD', '2018', '978-602-5792-40-3', 'Buku Madilog karya Tan Malaka adalah sebuah karya filosofis yang menggabungkan Marxisme, Leninisme, dan Logika. Buku ini membahas teori materialisme dialektika dan logika, serta aplikasinya dalam analisis sosial dan politik. Tan Malaka menguraikan pemikiran-pemikiran filosofisnya secara sistematis, mencakup konsep-konsep seperti materi, kesadaran, dialektika, dan logika. Buku ini tidak hanya memperkenalkan konsep-konsep dasar dalam pemikiran Tan Malaka tetapi juga mengajukan kritik terhadap kapitalisme, imperialisme, dan kolonialisme. Selain itu, Madilog juga membahas strategi revolusioner dan perjuangan kelas yang diadvokasi oleh Tan Malaka dalam konteks perjuangan kemerdekaan Indonesia.', 'https://www.goodreads.com/book/show/1607269.Madilog?ref=nav_sb_ss_1_7'),

('15', 'Non Fiksi', 'Islam dan Sosialisme', 'H.O.S Tjokroaminoto', 'Tride', 'Oktober 2003', '979-97816-3-9', 'Buku Islam dan Sosialisme karya H.O.S. Tjokroaminoto membahas pandangan dan pemikiran tokoh-tokoh Islam mengenai hubungan antara Islam dan sosialisme. Tjokroaminoto, seorang pemimpin reformis Islam Indonesia pada awal abad ke-20, merumuskan pandangan bahwa Islam dan sosialisme dapat saling mendukung dalam memperjuangkan keadilan sosial. Buku ini menguraikan argumentasi bahwa nilai-nilai Islam seperti keadilan, persaudaraan, dan kebersamaan sejalan dengan prinsip-prinsip sosialisme. Tjokroaminoto menekankan pentingnya bagi umat Islam untuk terlibat dalam perjuangan sosial dan politik, dengan landasan moral dari ajaran Islam sebagai pedoman. Namun demikian, Tjokroaminoto juga mempertimbangkan perbedaan mendasar antara Islam dan sosialisme, seperti pandangan tentang kepemilikan pribadi dan struktur sosial. Buku ini memberikan wawasan yang mendalam tentang bagaimana pemikiran Islam moderat dapat berinteraksi dengan ideologi sosialisme, mencoba menyatukan elemen-elemen positif dari kedua tradisi tersebut untuk kemajuan sosial dan keadilan.', 'H.O.S Tjokroaminoto'),

('16', 'Non Fiksi', 'Pemikiran Politik Islam di Indonesia: Teori, Sejarah, dan Praktik', 'Muhammad Iqbal Ahnaf', 'PT LKiS Pelangi Aksara', '2017', '978-602-231-678-6', 'Buku Pemikiran Politik Islam di Indonesia: Teori, Sejarah, dan Praktik karya Muhammad Iqbal Ahnaf merupakan kajian mendalam terhadap pemikiran politik Islam di Indonesia. Penulis menganalisis evolusi pemikiran politik Islam dari masa pra-kemerdekaan hingga era reformasi, serta peran dan pengaruhnya terhadap dinamika politik di Indonesia. Buku ini membahas berbagai teori politik Islam, sejarah gerakan politik Islam di Indonesia, dan aplikasi praktis dari pemikiran politik Islam dalam kehidupan politik kontemporer. Muhammad Iqbal Ahnaf juga menyoroti perbedaan pandangan di dalam gerakan politik Islam, dari moderat hingga yang lebih radikal, serta dampaknya terhadap perkembangan demokrasi dan negara Indonesia.', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=1185711'),

('17', 'Biografi', 'Bung Karno: Penyambung Lidah Rakyat Indonesia', 'Cindy Adams', 'Ufuk Press', '2018', '978-602-5795-57-2', 'Buku Bung Karno: Penyambung Lidah Rakyat Indonesia karya Cindy Adams mengisahkan kehidupan dan perjuangan Bung Karno, Presiden pertama Indonesia. Buku ini mengungkapkan berbagai aspek dari kehidupan Bung Karno, termasuk latar belakang keluarganya, perannya dalam perjuangan kemerdekaan Indonesia, serta pemikiran dan visinya tentang negara dan politik. Cindy Adams juga menyoroti kepemimpinan Bung Karno dalam membangun Indonesia pasca-kemerdekaan, tantangan yang dihadapinya, serta pandangan politiknya yang unik. Buku ini memberikan wawasan mendalam tentang salah satu tokoh terpenting dalam sejarah Indonesia, yang berperan dalam pembentukan dan pengembangan negara Indonesia modern.', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=1253900'),

('18', 'Non Fiksi', 'Kebudayaan dan Kependudukan Indonesia', 'Koentjaraningrat', 'Dian Rakyat', '1978', '979-501-286-4', 'Buku Kebudayaan dan Kependudukan Indonesia karya Koentjaraningrat membahas interaksi antara kebudayaan dan kependudukan dalam masyarakat Indonesia. Koentjaraningrat, seorang antropolog terkemuka Indonesia, menggambarkan keragaman kebudayaan di Indonesia dan bagaimana kebudayaan memengaruhi perilaku dan kehidupan sosial masyarakat. Buku ini juga menyoroti faktor-faktor yang mempengaruhi kependudukan di Indonesia, termasuk pola migrasi, urbanisasi, dan pengaruh globalisasi terhadap kebudayaan tradisional. Koentjaraningrat menawarkan analisis yang mendalam tentang hubungan antara kebudayaan dan kependudukan, serta implikasinya dalam konteks pembangunan dan modernisasi di Indonesia.', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=19587'),

('19', 'Non Fiksi', 'Agama, Sains, dan Masyarakat', 'Abdul Malik Karim Amrullah (Hamka)', 'Pustaka Panjimas', '2018', '978-979-3613-88-8', 'Buku Agama, Sains, dan Masyarakat karya Hamka membahas hubungan antara agama Islam, sains, dan masyarakat modern. Hamka, seorang ulama dan intelektual Indonesia, mengeksplorasi konsep-konsep dasar dalam agama Islam dan bagaimana mereka berhubungan dengan ilmu pengetahuan dan masyarakat. Buku ini menguraikan pemikiran Hamka tentang sains dan agama, serta pentingnya pendekatan yang seimbang antara keduanya dalam memandu kehidupan manusia. Hamka juga membahas implikasi sosial dan moral dari kemajuan sains modern, serta tantangan-tantangan yang dihadapi dalam mempertahankan nilai-nilai keagamaan dalam dunia yang semakin modern dan kompleks.', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=1388494'),

('20', 'Non Fiksi', 'Ekonomi Politik Media: Perspektif Kritis atas Kekuasaan Media', 'Rosalind Gill', 'Pustaka Pelajar', '2017', '978-602-425-732-0', 'Buku Ekonomi Politik Media: Perspektif Kritis atas Kekuasaan Media karya Rosalind Gill mengkaji hubungan antara ekonomi, politik, dan media dalam konteks globalisasi dan digitalisasi. Gill menganalisis bagaimana media massa memainkan peran kunci dalam mempengaruhi opini publik, membangun narasi politik, dan memengaruhi kebijakan publik. Buku ini menguraikan teori-teori ekonomi politik media, serta memberikan studi kasus yang menjelaskan bagaimana media mengontrol dan dimanipulasi oleh kepentingan ekonomi dan politik tertentu. Rosalind Gill juga menawarkan perspektif kritis terhadap industri media kontemporer, menyoroti bagaimana media dapat menjadi alat kekuasaan yang mempengaruhi masyarakat dan politik global.', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=1171712'),

('21', 'Non Fiksi', 'Ensiklopedia Akhir Zaman', 'M. Ahmad Al-Mubayyadh', 'Granada Mediatama', 'November 2018', '978-979-3693-12-5', 'Buku ini menjelaskan tentang status hadits/ atsar yang termuat, penjelasan makna dari kosakata hadits dan penjelasan kontekstual hadits tersebut secara realita kekinian, menyebutkan tanda kiamat kecil di masa nabi, tanda kiamat di era sahabat, tanda kiamat kecil yang terjadi pada salaf yang masih terus berlangsung hingga zaman sekarang, tanda kiamat kecil yang telah jelas maknanya, tanda kiamat kecil yang belum jelas maknanya, pra kondisi menuju tanda-tanda kiamat kubra, dan lainnya. Banyak sekali memaparkan hadits-hadits yang jarang ditemukan dalam pembahasan tentang fitnah dan petaka akhir zaman. Hadits tentang munculnya kendaraan setan (mobil), hadits tentang An-Nafsu Zakiyah yang terbunuh sebelum datangnya Al-Mahdi, hadits tentang hujan meteor sebelum keluarnya Dajjal, dan riwayat-riwayat lain yang membuat kita takjub, dan yang terpenting banyak memaparkan solusi dan langkah yang harus diambil oleh kaum muslimin dalam menghadapi berbagai persoalan fitnah yang menimpa mereka.', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=1164682'),

('22', 'Novel', 'Teruslah Bodoh Jangan Pintar', 'Tere Liye', 'Sabak Grip Nusantara', 'Februari 2024', '978-979-3693-12-5', 'Teruslah Bodoh Jangan Pintar karya Tere Liye adalah sebuah novel yang mengisahkan perjuangan dua aktivis melawan PT Semesta Mineral & Mining dalam sebuah persidangan. Aktivis ini menggugat perusahaan tambang tersebut di hadapan komite yang baru dibentuk oleh presiden baru. Mereka didukung oleh berbagai rekan dari profesi berbeda, termasuk seorang pembuat film, seorang jurnalis, dan seorang pemilik warung kopi. Persidangan tersebut sangat kompleks, dengan banyak saksi dari pihak aktivis yang menghadirkan bukti dampak negatif langsung dari operasi tambang PT Semesta Mineral & Mining. Mereka harus berhadapan dengan pengacara ternama yang selalu berhasil memenangkan kasus-kasus persidangan yang dia tangani, yang dipekerjakan oleh PT Semesta Mineral & Mining untuk membela mereka.', 'https://www.goodreads.com/book/show/207861795-teruslah-bodoh-jangan-pintar?ref=nav_sb_ss_1_29'),

('23', 'Pengembangan Diri', 'Bicara Itu Ada Seninya', 'Oh Su Hyang', 'Bhuana Ilmu Popuer', 'April 2018', '978-623-04-0430-6', 'Buku Teknik Komunikasi karya Oh Su Hyang menghadirkan panduan yang menyeluruh dan inspiratif tentang seni berbicara yang efektif. Meskipun judulnya mungkin mengecoh, buku ini tidak hanya membahas teknik-teknik komunikasi, tetapi juga menggali aspek-aspek penting dalam berinteraksi manusia. Dengan gaya penulisan yang jelas dan lugas, Oh Su Hyang, seorang pakar komunikasi terkemuka dari Korea Selatan, memandu pembaca melalui lima bab yang terstruktur dengan baik. Bab pertama buku ini dimulai dengan testimoni dari berbagai tokoh terkenal, mengilustrasikan betapa pentingnya kesan pertama yang dibangun dari ucapan. Bab ini memberikan dasar yang kuat untuk memahami bagaimana kata-kata dapat mempengaruhi persepsi orang lain terhadap kita. Sementara itu, bab kedua membahas tentang pentingnya mendengarkan dengan baik dan bagaimana kita dapat berbicara dengan lebih efektif menggunakan teknik komunikasi yang terbukti. Buku ini juga mengajarkan cara membuat lawan bicara mendukung kita melalui teknik-teknik berdiskusi yang cerdas, dan menegaskan pentingnya isi yang dalam dalam setiap ucapan. Bab terakhir menambahkan dimensi lain dengan menghadirkan kisah-kisah inspiratif dari tokoh-tokoh dunia yang menggunakan kemampuan berbicara mereka sebagai kunci sukses.', 'https://www.goodreads.com/book/show/43397364-bicara-itu-ada-seninya?ref=nav_sb_ss_1_23'),

('24', 'Pengembangan Diri', 'Nanti Kita Cerita Tentang Hari Ini', 'Marchella FP', 'POP', 'Januari 2018', '978-602-481-318-5', 'Nanti Kita Cerita Tentang Hari Ini mengisahkan tentang sebuah keluarga yang terjebak dalam rahasia gelap masa lalu yang meruntuhkan. Dengan detail yang penuh emosi, novel ini memaparkan bagaimana konflik yang terpendam bisa mengancam keharmonisan keluarga yang sebelumnya terlihat sempurna. Ketika rahasia kelam tentang kembaran almarhum adik bungsunya terungkap, keluarga ini terpaksa menghadapi masa lalu mereka yang menyakitkan. Sang ayah, yang berusaha untuk melindungi keluarganya dengan menyembunyikan kebenaran, akhirnya harus membuka pintu pada masa lalu yang terpendam untuk memulihkan kedamaian keluarga. Proses pengungkapan ini tidak hanya membawa rasa sakit dan kekecewaan, tetapi juga memungkinkan keluarga untuk tumbuh dan menguat bersama dalam menghadapi tantangan hidup. Novel ini tidak hanya menggugah emosi tetapi juga menginspirasi dengan pesan tentang pentingnya kejujuran dan pengampunan dalam membangun hubungan yang sehat. Dengan gaya narasi yang memikat, penulis berhasil menggambarkan perjalanan panjang keluarga ini menuju penerimaan dan perdamaian. Nanti Kita Cerita Tentang Hari Ini adalah pengingat yang kuat tentang bagaimana menghadapi masa lalu yang sulit dapat membawa keluarga menuju kehidupan yang lebih harmonis dan penuh makna.', 'https://www.goodreads.com/book/show/42435393-nanti-kita-cerita-tentang-hari-ini?ref=nav_sb_ss_1_34'),

('25', 'Novel', 'Negeri Para Bedebah', 'Tere Liye', 'Gramedia Pustaka Utama', 'Juli 2012', '978-602-03-8829-8', 'Negeri Para Bedebah karya Tere Liye mengisahkan Thomas, seorang konsultan keuangan terkenal dengan latar belakang kelam sebagai anak yatim piatu yang tumbuh di asrama. Ketika saudara kandungnya, pemilik Bank Semesta, Mr. Liem, tersandung kasus hukum serius, Thomas awalnya enggan membantu karena masa lalu kelamnya dengan keluarga Mr. Liem. Namun, demi melihat kondisi buruk tante Mr. Liem, Thomas setuju membantu dan berhasil meloloskan Mr. Liem dari penangkapan polisi. Mereka berusaha menyelamatkan Bank Semesta dari kebangkrutan dengan mendapatkan pinjaman dari pemerintah, meskipun mereka menghadapi banyak rintangan termasuk serangan polisi dan konspirasi politik. Thomas dan Julia, seorang reporter muda, akhirnya mengungkap masa lalu gelap Thomas, termasuk tragedi kebakaran yang menewaskan orang tuanya, serta menjalin persekutuan untuk menghadapi intrik dan kriminalitas dalam dunia perbankan.', 'https://www.goodreads.com/book/show/15721334-negeri-para-bedebah?from_search=true&from_srp=true&qid=uX1sfx4CrL&rank=1'),

('26', 'Novel', 'Negeri Di Ujung Tanduk', 'Tere Liye', 'Gramedia Pustaka Utama', 'April 2013', '978-602-03-6210-6', 'Novel Negeri Di Ujung Tanduk karya Tere Liye mengisahkan Thomas yang kembali terlibat dalam dunia politik yang kompleks. Thomas berusaha membantu kliennya keluar dari berbagai kasus korupsi untuk menjadikannya kandidat partai yang bersih. Buku ini mengangkat isu-isu politik yang rumit, memperlihatkan kompleksitas dunia politik yang penuh dengan zona abu-abu, di mana sulit membedakan mana yang benar dan salah. Tere Liye dengan tajam menggambarkan baik buruknya dunia perpolitikan, di mana setiap negara memiliki warna politiknya sendiri dengan masalah yang berbeda.', 'https://www.goodreads.com/book/show/17566144-negeri-di-ujung-tanduk?ref=nav_sb_ss_1_22'),

('27', 'Novel', 'Pulang', 'Tere Liye', 'Republika', 'Oktober 2015', '978-602-0822-12-9', 'Novel Pulang karya Tere Liye mengisahkan perjalanan hidup Bujang, seorang anak laki-laki yang mengalami kehidupan sulit di hutan rimba Sumatra sejak usia 15 tahun, terancam oleh monster mengerikan. Dia kemudian diambil oleh Teuku Muda, seorang bos mafia yang dekat dengan ayahnya, untuk diberi pendidikan dan melihat dunia luar meskipun sang ibu enggan melepaskannya. Bujang mengalami berbagai tragedi, seperti kematian kedua orangtuanya, kepergian Kopong yang setia, dan pengkhianatan Basyir. Setelah menyelesaikan kuliahnya, dia menghadapi pengkhianatan dari teman dekatnya, Basyir. Namun, perjumpaannya dengan Tuanku Imam mengungkapkan asal-usul keluarganya dan makna Pulang. Bujang akhirnya memahami alasan sang ayah menjadikannya anak angkat Teuku Muda, terkait keterlibatan ayahnya dalam bisnis Shadow Economy. Meskipun awalnya menolak, Bujang mewarisi keahlian sebagai jagal dari ayah dan kakeknya, terlibat dalam bisnis keluarga Tong di dunia hitam, dan naik menjadi pemimpin keluarga Tong atas anugerah Teuku Muda.', 'https://www.goodreads.com/book/show/26211806-pulang?ref=nav_sb_ss_1_6'),

('28', 'Novel', 'Pergi', 'Tere Liye', 'Republika', 'Maret 2018', '978-602-5734-05-2', 'Novel ini mengisahkan Bujang, tokoh utama dari novel sebelumnya Pulang karya Tere Liye. Bujang kini sibuk sebagai pentolan keluarga Tong, sebuah keluarga dalam dunia shadow economy yang rumit. Setelah kehilangan orang-orang terdekatnya seperti mamak, Tauke besar, dan beberapa guru, Bujang tinggal di markas keluarga Tong di ibu kota. Dalam cerita ini, Bujang bekerja sama dengan Togar dan Parwez untuk mengembangkan keluarga Tong ke arah yang lebih baik. Di tengah perjalanannya, Bujang bertemu dengan Thomas, tokoh dari novel Negeri Para Bedebah dan Negeri di Ujung Tanduk, serta beberapa kepala keluarga dari shadow economy lainnya. Mereka berhadapan dengan sosok bertopeng misterius di Meksiko yang mengetahui nama asli Bujang, yang tidak sembarang orang tahu.', 'https://www.goodreads.com/book/show/39643727-pergi?ref=nav_sb_ss_1_5'),

('29', 'Novel', 'Pulang - Pergi', 'Tere Liye', 'Republika', 'Januari 2021', '978-623-95545-2-1', 'Novel Pulang-Pergi mengisahkan Bujang, mantan tukang pukul terkenal dari keluarga shadow economy. Saat berziarah ke makam orangtuanya, Bujang diserang oleh Natascha, orang kepercayaan Otets, pemimpin Brotherhood Bratva. Natascha menyampaikan pesan agar Bujang datang ke acara pertunangan dengan putri Otets, Maria, atau akan terjadi perang besar. Bujang menemui Otets untuk bernegosiasi agar pertunangan ditunda, tapi Otets langsung mengubahnya menjadi pernikahan. Pada hari pernikahan, Otets dibunuh oleh Natascha, yang ingin mengambil alih kepemimpinan Bratva dengan mengeliminasi Bujang, Maria, Salonga, dan Junior. Bujang dan kawan-kawan berusaha melawan Natascha dan para pembunuh bayaran yang mengejar mereka, mencari bantuan untuk melawan balik Natascha.', 'https://www.goodreads.com/book/show/56459890-pulang-pergi?ref=nav_sb_ss_1_14'),

('30', 'Novel', 'Laskar Pelangi', 'Andrea Hirata', 'Bentang Pustaka', 'Januari 2015', '978-602-291-662-8', 'Novel Laskar Pelangi mengisahkan perjalanan sepuluh anak dari keluarga kurang mampu di Desa Gantung, Belitong Timur, yang bersekolah di sekolah Muhammadiyah. Ketika sekolah mereka hampir ditutup karena minimnya siswa, datanglah Harun yang melengkapi jumlah minimal sepuluh siswa untuk mempertahankan sekolah itu. Mereka dikenal sebagai Laskar Pelangi karena kegemaran mereka memandangi pelangi. Mereka hidup dalam komunitas tambang di Belitung, di mana pendidikan terbatas hanya untuk anak-anak pegawai PN Timah. Meskipun dalam kondisi ekonomi dan pendidikan yang tertinggal, anak-anak ini tidak menyerah dan tetap mempertahankan semangat belajar. Mereka berjuang untuk menjaga sekolah tetap beroperasi dan meraih prestasi, seperti penampilan tarian Mahar dalam festival 17 Agustus dan kemenangan Lintang dalam lomba cerdas cermat. Novel ini menyoroti bahwa kemiskinan bukanlah penanda ketidakmampuan dan bahwa pendidikan adalah kunci untuk mengatasi keterbatasan tersebut. Laskar Pelangi juga menggambarkan persahabatan yang penuh tawa dan tangis, menghadirkan kisah haru tentang perjuangan ayah Lintang untuk menyekolahkan putranya. Meskipun dihadapkan pada berbagai rintangan, mereka akhirnya berhasil meraih impian mereka dengan pencapaian luar biasa.', 'https://www.goodreads.com/book/show/1362193.Laskar_Pelangi?ref=nav_sb_ss_1_14'),

('31', 'Novel', 'Ayah', 'Andrea Hirata', 'Bentang Pustaka', 'Mei 2015', '978-602-291-102-9', 'Novel ini mengisahkan tentang Sabari, seorang lelaki yang mencintai Marlena sejak pertama kali mereka bertemu di masa remaja. Meskipun Marlena tidak pernah mencintainya dengan sepenuh hati, Sabari bersedia menikahinya dan menjadi ayah bagi anak Marlena, Zorro. Meskipun hidup rumah tangganya tidak bahagia, Sabari sangat mencintai Zorro dan menjadikannya pusat dunianya setelah Marlena pergi dengan Zorro dan bercerai. Setelah itu, Sabari merasa kehilangan gairah hidupnya, berhenti bekerja, dan hidup dalam keterpurukan. Sahabatnya, Ukun, Tamat, dan Toharun, merasa iba melihat keadaannya dan berusaha untuk membantu Sabari dengan menemui Marlena dan mempertemukan Zorro kembali dengan ayahnya agar Sabari dapat kembali pulih.', 'https://www.goodreads.com/book/show/25498974-ayah?ref=nav_sb_ss_1_5'),

('32', 'Novel', 'Bedebah di Ujung Tanduk', 'Tere Liye', 'Sabak Grip Nusantara', 'Oktober 2021', '978-623-97262-1-8', 'Novel Bedebah di Ujung Tanduk karya Tere Liye adalah sekuel yang menggabungkan dua karakter utama dari novel sebelumnya, Thomas dari Negeri Para Bedebah dan Negeri di Ujung Tanduk serta Bujang dari Si Babi Hutan. Cerita ini mengisahkan Thomas yang terlibat dalam transaksi besar yang membangkitkan kemarahan musuh lama, mempengaruhi dunia ekonomi bayangan yang dikuasai Bujang. Alur cerita maju terus dengan penuh ketegangan, mempertemukan pembaca dengan tokoh-tokoh yang hidup dan nyata. Keberanian Tere Liye dalam mengangkat isu-isu aktual membuat buku ini sangat menarik.', 'https://www.goodreads.com/book/show/59386056-bedebah-di-ujung-tanduk?ref=nav_sb_ss_1_23'),

('33', 'Novel', 'Tanah Para Bandit', 'Tere Liye', 'Sabak Grip Nusantara', 'Februari 2023', '978-623-88296-7-5', 'Novel Tanah Para Bandit mengambil latar belakang di Talang, yang dikenal sebagai tempat yang melahirkan para penjahat dan bandit. Selain Bujang, ada seorang gadis remaja bernama Padma yang juga menjadi fokus cerita. Padma dilatih untuk menjalankan misi oleh sebuah organisasi misterius yang bertujuan memberantas kejahatan di balik layar. Karakter Padma dibangun dengan baik, menunjukkan prosesnya untuk menjadi sosok yang tangguh melalui latihan fisik dan mental yang keras. Novel ini mengungkap sisi gelap institusi negara dan relevan dengan peristiwa-peristiwa kontemporer seperti pembunuhan, narkoba, korupsi, dan penyelundupan barang ilegal. Alur cerita maju dengan baik, diceritakan secara langsung tanpa bertele-tele, setiap halaman memiliki peran penting dalam kesatuan buku. Tere Liye juga menyelipkan pengetahuan baru tentang tumbuhan beracun, ekonomi, dan hukum yang menambah wawasan pembaca.', 'https://www.goodreads.com/book/show/85174373-tanah-para-bandit?ref=nav_sb_ss_1_17'),

('34', 'Novel', 'Bintang', 'Tere Liye', 'Gramedia Pustaka Utama', 'Juni 2017', '978-602-03-5117-9', 'Raib, Seli, dan Ali adalah tiga teman SMA yang menyimpan rahasia besar. Raib, keturunan klan Bulan, memiliki kekuatan menghilang. Seli, dari klan Matahari, mampu mengeluarkan petir. Ali, dari klan Bumi, bisa berubah menjadi beruang. Mereka bersatu untuk melawan rencana jahat Dewan Kota Zaramaraz dari Klan Bintang yang ingin menghancurkan klan permukaan dengan merusak pasak bumi. Bersama dengan teman-teman mereka, mereka menjelajahi lorong-lorong kuno di Klan Bintang untuk menemukan dan menyegel pasak bumi yang berpotensi membahayakan. Setelah menghadapi berbagai rintangan dan bahaya, termasuk pengejaran dari Pasukan Bintang, mereka berhasil menemukan pasak bumi yang berbahaya. Namun, ketika mereka kembali untuk melaporkan penemuan mereka kepada Miss Selena, guru Matematika mereka, mereka mendapat kekecewaan karena reaksi Miss Selena yang hampir marah terhadap mereka.', 'https://www.goodreads.com/book/show/35278713-bintang?ref=nav_sb_ss_2_7'),

('35', 'Novel', 'Hello', 'Tere Liye', 'Sabak Grip Nusantara', 'April 2023', '978-623-88296-8-2', 'Ana, seorang arsitek muda yang ambisius, bertemu dengan Hesty, seorang klien istimewa yang ingin merenovasi rumah peninggalan orang tuanya. Ana terlibat dalam kisah cinta Hesty dan Tigor, dua sahabat masa kecil yang terpisah karena perbedaan status sosial. Novel ini menceritakan perjalanan cinta Hesty dan Tigor yang penuh rintangan. Meskipun mereka saling mencintai, perbedaan latar belakang dan penolakan dari ayah Hesty membuat mereka harus berpisah. Bertahun-tahun kemudian, Ana membantu Hesty dan Tigor untuk bersatu kembali dan mewujudkan mimpi mereka. Novel ini tentang cinta, persahabatan, dan perjuangan untuk mencapai mimpi, menunjukkan bahwa cinta sejati dapat mengalahkan segala rintangan.', 'https://www.goodreads.com/book/show/140360896-hello?from_search=true&from_srp=true&qid=yUoDGA00Jc&rank=42'),

('36', 'Pengembangan Diri', 'Filosofi Teras', 'Henry Manampiring', 'Kompas Media Nusantara', 'November 2018', '978-623-346-303-4', 'Filosofi Teras membawa pembaca masuk ke dalam suasana yang penuh energi positif dan kehidupan yang tenang, sesuai dengan idaman banyak orang. Henry Manampiring berhasil menghadirkan buku yang tidak hanya mengulas tentang Stoisisme, tetapi juga mempersembahkan insight pribadi dan perspektif praktisi dari berbagai bidang. Meskipun buku ini diakui tidak secara menyeluruh menjelaskan filosofi Stoisisme, namun inti-nilai yang disampaikan sangat mudah dipahami dan relevan untuk kehidupan sehari-hari. Dalam Filosofi Teras, pembaca dibawa untuk merenungkan nilai-nilai Stoisisme dengan cara yang menarik. Buku ini seperti hidangan pembuka yang menggugah selera untuk menjelajahi lebih dalam tentang ajaran Stoisisme atau Stoa. Dengan membaca buku ini, kita tidak hanya diajak untuk memahami konsep-konsep penting, tetapi juga untuk merenungkan dan menerapkan nilai-nilai tersebut dalam kehidupan kita. Sebuah karya yang layak mendapat penghargaan, karena mampu memperkaya karakter pembacanya dan menginspirasi perkembangan pribadi, meskipun tentunya tidak semua prinsip yang dijelaskan cocok untuk semua orang dalam semua kondisi.', 'https://www.goodreads.com/book/show/42861019-filosofi-teras?ref=nav_sb_ss_1_14'),

('37', 'Pengembangan Diri', 'Berani Tidak Disukai', 'Ichiro Kishimi & Fumitake Koga', 'Gramedia Pustaka Utama', 'Oktober 2019', '978-602-06-3321-3', 'Buku \'Berani Tidak Disukai\' mengungkapkan kekuatan terpendam dalam mencapai kebahagiaan hakiki yang kita pilih sendiri. Karya ini tidak hanya membahas teori-teori psikologi seperti Alfred Adler, yang menawarkan pandangan baru terhadap kebahagiaan yang tidak terpengaruh oleh masa lalu, tetapi juga mengajak pembaca untuk mempertimbangkan bagaimana cara menghadapi tantangan dan mengubah perspektif terhadap kehidupan. Dengan menekankan pentingnya menerima diri sendiri dan membangun keberanian untuk mengejar impian, buku ini memberi pencerahan tentang bagaimana mengatasi rasa minder dan menemukan kedamaian dalam hidup. Buku ini bukan hanya sekadar panduan tentang bagaimana menemukan kebahagiaan pribadi, tetapi juga sebuah ajakan untuk memahami bahwa hidup bukan tentang mendapatkan pengakuan dari orang lain, melainkan tentang menerima diri dan mengambil tanggung jawab atas kehidupan kita sendiri. Dengan menggabungkan teori psikologi Adler dengan pendekatan yang praktis dan inspiratif, \'Berani Tidak Disukai\' adalah buku yang memotivasi untuk menjalani hidup dengan keberanian, menerima diri sendiri, dan menemukan kebahagiaan yang sesungguhnya.', 'https://www.goodreads.com/book/show/52540429-berani-tidak-disukai?ref=nav_sb_ss_1_20'),

('38', 'Pengembangan Diri', 'Atomic Habits', 'James Clear', 'Avery', 'Oktober 2018', '978-602-06-3317-6', 'Atomic Habits karya James Clear adalah panduan praktis yang menggali kekuatan kebiasaan kecil dalam mencapai perubahan besar dalam hidup. Clear membawa pembaca melalui proses ilmiah dan psikologis untuk memahami bagaimana kebiasaan terbentuk, dan bagaimana kita dapat menggunakan pengetahuan ini untuk merancang kehidupan yang lebih baik. Dengan pendekatan yang jelas dan terstruktur, Clear mengajarkan cara mengubah kebiasaan buruk menjadi kebiasaan baik dengan memanfaatkan konsep-konsep seperti hukum pembiasaan, penggandaan identitas, dan peningkatan yang berkelanjutan. Buku ini tidak hanya memberikan tips praktis untuk membangun kebiasaan yang produktif, tetapi juga menawarkan wawasan mendalam tentang psikologi manusia dan ilmu perilaku. Dengan penekanan pada perubahan kecil yang konsisten, Atomic Habits mengilustrasikan bagaimana kecilnya perubahan dapat menghasilkan hasil yang besar dalam jangka panjang, membantu pembaca untuk mengatasi hambatan-hambatan yang menghalangi kemajuan mereka dan mencapai tujuan hidup dengan lebih efektif.', 'https://www.goodreads.com/book/show/40121378-atomic-habits?ref=nav_sb_ss_1_14'),

('39', 'Pengembangan Diri', 'How to Win Friends and Influence People', 'Dale Carnegie', 'Binarupa Aksara', 'September 2019', '978-979-583-606-3', 'How to Win Friends and Influence People oleh Dale Carnegie adalah buku klasik yang tetap relevan dalam dunia interpersonal modern. Carnegie mengajarkan prinsip-prinsip dasar yang dapat membantu pembaca membangun hubungan yang baik dengan orang lain dan memengaruhi mereka secara positif. Dengan fokus pada kejujuran, apresiasi, dan perhatian terhadap orang lain, Carnegie menunjukkan cara mengubah sikap dan perilaku kita untuk mencapai kesuksesan dalam kehidupan pribadi maupun profesional. Buku ini tidak hanya memberikan strategi praktis, tetapi juga membangun kesadaran akan pentingnya empati dan pemahaman terhadap kebutuhan orang lain. Melalui studi kasus yang mendalam dan anekdot inspiratif, Carnegie mengilustrasikan bagaimana menerapkan prinsip-prinsip ini dalam berbagai situasi kehidupan sehari-hari. Buku ini cocok untuk siapa saja yang ingin meningkatkan keterampilan sosial mereka, mengatasi konflik, dan membangun koneksi yang kuat dengan orang lain. Dengan membaca How to Win Friends and Influence People, pembaca akan mendapatkan wawasan yang mendalam tentang seni mempengaruhi dan membangun hubungan yang baik, serta menjadi lebih percaya diri dalam interaksi sosial mereka.', 'https://www.gramedia.com/products/how-to-win-friends-and-influence-people-1'),

('40', 'Pengembangan Diri', 'Ikigai', 'Hector Garcia', 'Renebook', 'Januari 2018', '978-602-1201-41-1', 'Ikigai adalah buku yang mendalami konsep Jepang tentang mencari makna dan tujuan hidup yang mendalam. Konsep ini mengajarkan bahwa setiap orang memiliki alasan hidup yang unik dan perlu ditemukan untuk mencapai kebahagiaan dan kesejahteraan yang sejati. Buku ini menggali bagaimana mencari dan mengaktualisasikan ikigai, serta memberikan panduan praktis untuk menemukan apa yang membuat hidup kita berarti dan memuaskan. Dengan pendekatan yang inspiratif dan penuh makna, Ikigai mengajarkan tentang arti kehidupan berdasarkan prinsip-prinsip Jepang yang dalam. Buku ini cocok untuk siapa saja yang ingin menjalani hidup dengan tujuan yang jelas dan merasa terhubung dengan apa yang mereka lakukan setiap hari. Dengan membaca Ikigai, pembaca akan diajak untuk merenungkan dan menemukan makna hidup mereka sendiri dalam konteks kehidupan modern yang serba kompleks.', 'https://www.goodreads.com/book/show/40534545-ikigai?ac=1'),

('36', 'Pengembangan Diri', 'Filosofi Teras', 'Henry Manampiring', 'Kompas Media Nusantara', 'November 2018', '978-623-346-303-4', 'Filosofi Teras membawa pembaca masuk ke dalam suasana yang penuh energi positif dan kehidupan yang tenang, sesuai dengan idaman banyak orang. Henry Manampiring berhasil menghadirkan buku yang tidak hanya mengulas tentang Stoisisme, tetapi juga mempersembahkan insight pribadi dan perspektif praktisi dari berbagai bidang. Meskipun buku ini diakui tidak secara menyeluruh menjelaskan filosofi Stoisisme, namun inti-nilai yang disampaikan sangat mudah dipahami dan relevan untuk kehidupan sehari-hari.', 'https://www.goodreads.com/book/show/42861019-filosofi-teras?ref=nav_sb_ss_1_14'),

('37', 'Pengembangan Diri', 'Berani Tidak Disukai', 'Ichiro Kishimi & Fumitake Koga', 'Gramedia Pustaka Utama', 'Oktober 2019', '978-602-06-3321-3', 'Buku Berani Tidak Disukai mengungkapkan kekuatan terpendam dalam mencapai kebahagiaan hakiki yang kita pilih sendiri. Karya ini tidak hanya membahas teori-teori psikologi seperti Alfred Adler, yang menawarkan pandangan baru terhadap kebahagiaan yang tidak terpengaruh oleh masa lalu, tetapi juga mengajak pembaca untuk mempertimbangkan bagaimana cara menghadapi tantangan dan mengubah perspektif terhadap kehidupan. Dengan menekankan pentingnya menerima diri sendiri dan membangun keberanian untuk mengejar impian, buku ini memberi pencerahan tentang bagaimana mengatasi rasa minder dan menemukan kedamaian dalam hidup.', 'https://www.goodreads.com/book/show/52540429-berani-tidak-disukai?ref=nav_sb_ss_1_20'),

('38', 'Pengembangan Diri', 'Atomic Habits', 'James Clear', 'Avery', 'Oktober 2018', '978-602-06-3317-6', 'Buku Atomic Habits karya James Clear adalah panduan praktis yang menggali kekuatan kebiasaan kecil dalam mencapai perubahan besar dalam hidup. Clear membawa pembaca melalui proses ilmiah dan psikologis untuk memahami bagaimana kebiasaan terbentuk, dan bagaimana kita dapat menggunakan pengetahuan ini untuk merancang kehidupan yang lebih baik. Dengan pendekatan yang jelas dan terstruktur, Clear mengajarkan cara mengubah kebiasaan buruk menjadi kebiasaan baik dengan memanfaatkan konsep-konsep seperti hukum pembiasaan, penggandaan identitas, dan peningkatan yang berkelanjutan.', 'https://www.goodreads.com/book/show/40121378-atomic-habits?ref=nav_sb_ss_1_14'),

('39', 'Pengembangan Diri', 'How to Win Friends and Influence People', 'Dale Carnegie', 'Binarupa Aksara', 'September 2019', '978-979-583-606-3', 'Buku How to Win Friends and Influence People oleh Dale Carnegie adalah buku klasik yang tetap relevan dalam dunia interpersonal modern. Carnegie mengajarkan prinsip-prinsip dasar yang dapat membantu pembaca membangun hubungan yang baik dengan orang lain dan memengaruhi mereka secara positif. Dengan fokus pada kejujuran, apresiasi, dan perhatian terhadap orang lain, Carnegie menunjukkan cara mengubah sikap dan perilaku kita untuk mencapai kesuksesan dalam kehidupan pribadi maupun profesional. Buku ini tidak hanya memberikan strategi praktis, tetapi juga membangun kesadaran akan pentingnya empati dan pemahaman terhadap kebutuhan orang lain.', 'https://www.gramedia.com/products/how-to-win-friends-and-influence-people-1'),

('40', 'Pengembangan Diri', 'Ikigai', 'Hector Garcia', 'Renebook', 'Januari 2018', '978-602-1201-41-1', 'Ikigai adalah buku yang mendalami konsep Jepang tentang mencari makna dan tujuan hidup yang mendalam. Konsep ini mengajarkan bahwa setiap orang memiliki alasan hidup yang unik dan perlu ditemukan untuk mencapai kebahagiaan dan kesejahteraan yang sejati. Buku ini menggali bagaimana mencari dan mengaktualisasikan ikigai, serta memberikan panduan praktis untuk menemukan apa yang membuat hidup kita berarti dan memuaskan.', 'https://www.goodreads.com/book/show/40534545-ikigai?ac=1&from_search=true&qid=r6n7VAHEPO&rank=1'),

('41', 'Pengembangan Diri', 'Sebuah Seni untuk Bersikap Bodoamat', 'Mark Manson', 'Gramedia Widiasarana Indonesia', 'Februari 2018', '978-602-452-698-6', 'Novel Sebuah Seni untuk Bersikap Bodo Amat mengisahkan kisah nyata Charles Bukowski, yang penuh dengan kegagalan, ketidakberuntungan, dan ketegaran. Meskipun hidup dalam kebiasaan buruk seperti mabuk-mabukan dan berutang, Bukowski tetap memelihara mimpi menjadi seorang penulis terkenal. Meski karyanya ditolak berulang kali, dia tidak menyerah dan terus menulis hingga akhirnya meraih kesuksesan dengan novel pertamanya, Post Office. Bukowskis journey serves as a powerful reminder that success often comes after many failures, and that sometimes, a nonchalant attitude towards life\'s challenges can be the key to resilience and eventual triumph.', 'https://www.goodreads.com/book/show/38198823-sebuah-seni-untuk-bersikap-bodo-amat?ref=nav_sb_ss_1_35'),

('42', 'Pengembangan Diri', 'Attitude Is Everything', 'Jeff Keller', 'Renebook', 'Februari 2024', '978-623-6083-40-6', 'Attitude is Everything oleh Jeff Keller adalah buku yang menghadirkan pelajaran berharga tentang kekuatan sikap mental dalam mencapai kesuksesan dalam hidup. Melalui cuplikan cerita yang disajikan, pembaca diajak untuk memahami bahwa sikap positif adalah kunci untuk mengubah pandangan dan tindakan dalam menghadapi tantangan dan meraih tujuan hidup. Keller menggambarkan bagaimana pikiran kita memengaruhi keadaan kita, menjelaskan bahwa sikap positif bukan hanya tentang pandangan terhadap dunia, tetapi juga tentang keyakinan dan tindakan yang mengikuti. Dengan penekanan pada visualisasi, komitmen, dan pembelajaran dari masalah, buku ini memberikan pandangan menyeluruh tentang bagaimana menjalani kehidupan dengan sikap yang memungkinkan untuk mencapai potensi penuh kita.', 'https://www.gramedia.com/products/quantum-ikhlas-teknologi-aktivasi-kekuatan-hati-reborn?queryID=89d673418f6eb48493ce6a8b7eb2e637'),

('43', 'Pengembangan Diri', 'Make Your Bed', 'William H. McRaven', 'Renebook', 'Maret 2023', '978-623-6083-50-5', 'Pentingnya Memulai Hari dengan Benar: Merapikan tempat tidur setiap pagi seperti yang ditekankan oleh McRaven dalam bukunya memberikan suasana positif yang vital untuk memulai hari dengan semangat. Dengan fokus pada langkah sederhana ini, pembaca diajak untuk memahami pentingnya menjaga rutinitas kecil yang dapat membentuk dasar kepercayaan diri dan disiplin diri. Mengatasi Tantangan dan Membangun Kepercayaan Diri: Buku ini membahas strategi untuk mengatasi kesulitan dengan integritas, mengarah pada perkembangan kekuatan dan kesuksesan pribadi. Melalui pembahasan ini, pembaca dapat memperoleh wawasan yang kuat dalam memahami bagaimana menghadapi tantangan dengan keyakinan dan membangun kepercayaan diri yang kokoh. Hidup dengan Tujuan yang Jelas: Menurut McRaven, kehidupan dengan tujuan yang jelas adalah kunci untuk mencapai kebahagiaan dan kepuasan. Melalui bukunya, ia menyajikan pandangan yang kuat mengenai betapa pentingnya memiliki visi dan tujuan yang dapat memandu setiap tindakan dan keputusan dalam hidup . Pelajaran dan Inspirasi Utama: Buku ini menawarkan nasihat berharga untuk menghadapi berbagai rintangan dan membuat keputusan hidup yang bijaksana, menjadikannya sebagai panduan yang memotivasi pembaca untuk mencapai kemajuan dalam kehidupan sehari-hari.', 'https://gramedia.com/products/make-your-bed?queryID=a14863af5be2a7a39013f7e7e927bb05'),

('44', 'Sejarah', 'Shirah Nabawiyah', 'Ibn Hisyam', 'Darul Falah', 'Februari 2018', '978-602-9215-14-4', 'Buku Sirah Nabawiyah adalah rekaman menyeluruh dari kehidupan Nabi besar Muhammad Shalallahu ‘Alaihi wa Sallam, mulai dari masa kecil hingga wafat. Dengan detail dan kedalaman yang luar biasa, buku ini memungkinkan pembaca untuk menelusuri setiap aspek kehidupan Rasul dengan nuansa yang kaya dan penuh warna. Keunggulan utama dari buku ini adalah kemampuannya untuk merekam prosesi turunnya ayat-ayat Al-Quran kepada Nabi, memberikan konteks yang mendalam bagi pembaca. Diklaim sebagai sumber paling lengkap dan awal dari sejarah Nabi, buku ini menjadi rujukan utama untuk buku-buku sirah setelahnya, sehingga tidak ada yang dapat menandingi tingkat kepercayaan dan kualitasnya. Dipuji oleh sejarawan dan ulama, Sirah Nabawiyah oleh Ibnu Ishaq dan Ibnu Hisyam menjadi buku yang tidak hanya menginspirasi, tetapi juga membanggakan bagi para pembacanya, memberikan pengalaman tak tertandingi dalam memahami kehidupan Nabi', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=1080752'),

('45', 'Sejarah', 'Sejarah Dunia yang Disembunyikan', 'John Black', 'Pustaka Alvabet', 'November 2015', '978-602-6577-52-8', 'Buku Sejarah Dunia Yang Disembunyikan karya Jonathan Black mengundang pembaca untuk menjelajahi sisi gelap sejarah yang sering kali tersembunyi dari publik. Dengan menelusuri mitos, legenda, dan cerita rakyat dari berbagai budaya kuno, Black menghadirkan pandangan alternatif terhadap peristiwa-peristiwa besar dalam sejarah manusia. Dia mengajak pembaca untuk mempertanyakan ulang kebenaran sejarah yang diterima secara konvensional, mengungkapkan konspirasi-konspirasi rahasia dan menyajikan bukti-bukti yang mendalam tentang berbagai peristiwa yang terjadi di balik layar sejarah. Buku ini tidak hanya membangkitkan rasa ingin tahu terhadap rahasia-rahasia dunia, tetapi juga menggugah pembaca untuk berpikir lebih kritis dan terbuka terhadap perspektif baru. Dengan gaya bahasa yang jelas dan menghibur, Jonathan Black berhasil menggabungkan filosofi, teori-teori aneh, dan pengetahuan esoteris menjadi sebuah narasi yang memikat. Bagi siapa pun yang tertarik dengan sejarah alternatif dan ingin menjelajahi sisi-sisi gelap dari perjalanan manusia, buku ini merupakan bacaan yang kontroversial namun sangat memuaskan.', 'https://www.goodreads.com/book/show/28929991-sejarah-dunia-yang-disembunyikan?ref=nav_sb_ss_1_32'),

('46', 'Sejarah', 'Api Sejarah', 'Ahmad Mansur Suryanegara', 'Salamadani Pustaka Semesta', 'Juli 2009', '978-602-71237-1-7', 'Buku Api Sejarah berisi tentang sejarah perjuangan Indonesia yang belum pernah terungkap dan diungkap. Beberapa fakta sejarah seperti Indonesia yang telah diislamkan sejak lama dapat dilihat dari simbol-simbol keislaman seperti warna bendera Sang Saka Merah Putih yang diadaptasi dari warna Islam, bukan dari lambang Majapahit, pergerakan organisasi dan partai Islam yang mengupayakan kemerdekaan RI, sampai asal-usul beberapa pejuang Islam. Banyak fakta dan data yang “tersembunyi” dan “disembunyikan” yang diungkap dalam buku API SEJARAH memperkaya argumentasi. Diantaranya: Sejarah Masuk Islam ke Indonesia yang dimulai abad ke-1 dan 2 Hijriah sampai perjuangan para wali di Indonesia, Perjuangan Gerakan Islam melawan penjajah Belanda yang dimotori oleh para Ulama dan Santri. Masa masuk dan perkembangan Agama Islam di Nusantara Indonesia, sampai peran kekuasaan politik Islam melawan Imperialisme Barat. Termasuk membahas tentang Peran Ulama dalam Gerakan Kebangkitan Kesadaran Nasional (1900-1942).', 'https://www.goodreads.com/book/show/7226668-api-sejarah?ref=nav_sb_ss_1_11'),

('47', 'Sejarah', 'Api Sejarah 2', 'Ahmad Mansur Suryanegara', 'Salamadani Pustaka Semesta', 'Maret 2010', '978-602-71237-2-4', 'Api Sejarah 2 melanjutkan kupasan sejarah Indonesia. Buku kedua ini mengupas tentang “Peran Ulama Dalam Pembangunan Organisasi Militer Modern” dilanjutkan dengan “Peran Ulama Dalam Gerakan Protes Sosial dan Pemberontakan Tentara Pembela Tanah Air”, bab awal ini menunjukkan peran ulama pada masa pendudukan Jepang. Disajikan pula kupasan tentang ” Peran Ulama Dalam Menegakkan dan Mempertahankan Proklamasi” dan “Peran Ulama Menegakkan dan Mempertahankan Negara Kesatuan Republik Indonesia”, yang berkenaan dengan pasang surut peran ulama dalam masa revolusi Indonesia dan masa orde lama. Pembahasannya mencakup era reformasi yang mengupas bernas tentang “Langkah Penyesuaian Ulama dan Santri Di Era Orde Baru dan Reformasi”.', 'https://www.goodreads.com/book/show/8042560-api-sejarah-2?ref=nav_sb_ss_1_13'),

('48', 'Sejarah', 'Sapiens: Riwayat Singkat Umat Manusia', 'Yuval Noah Harari', 'Kepustakaan Populer Gramedia', 'Oktober 2017', '978-602-6577-17-7', 'Sapiens adalah sebuah perjalanan mendalam yang mengungkap evolusi manusia secara mengagumkan. Yuval Noah Harari mengambarkan tiga revolusi besar yang membentuk sejarah manusia: Revolusi Kognitif, Pertanian, dan Ilmiah. Melalui ringkasan yang penuh wawasan, Harari mengajak pembaca menjelajahi bagaimana kebudayaan, agama, dan kekuasaan manusia terbentuk dari ide-ide yang tidak ada secara fisik. Dengan gaya penulisan yang memikat, buku ini menggugah pemikiran tentang masa lalu, dan memberikan wawasan yang mendalam tentang bagaimana manusia telah mencapai dominasi atas dunia. Sapiens menjelaskan perjalanan panjang manusia, mempertanyakan realitas fisik dan imajinasi, serta bagaimana mitos dan keyakinan bersama membentuk masyarakat manusia. Dari revolusi kognitif hingga rekayasa genetika, Harari menyoroti transformasi yang mengubah tatanan dunia. Buku ini tidak hanya memberikan perjalanan sejarah yang memikat, tetapi juga mengajak pembaca untuk merenungkan tentang peran manusia di masa depan, menciptakan suasana yang menggelitik imajinasi dan memicu diskusi yang mendalam.', 'https://www.goodreads.com/book/show/36260835-sapiens?ref=nav_sb_ss_1_38'),

('49', 'Sejarah', 'Banjir Darah: Kisah Nyata Aksi PKI Terhadap Kiai, Santri, dan Kaum Muslimin', 'Anab Afifi & Thowaf Zuharon', 'Aqwam', 'Agustus 2020', '978-979-039-771-2', 'Buku Banjir Darah karya Anab Afifi adalah sebuah karya sejarah yang mengungkap kekejaman Partai Komunis Indonesia (PKI) pada tahun 1948-1965. Melalui kisah yang mencekam, buku ini menyoroti kekejaman PKI terhadap para kiai, ulama, santri, dan tokoh-tokoh yang berhubungan dengan organisasi Islam. Afifi membawa pembaca untuk menyelami masa-masa kelam tersebut, di mana PKI melakukan penyiksaan, pembunuhan, dan pengrusakan terhadap sarana ibadah dan pendidikan umat Muslim. Dengan gaya penulisan yang menggugah dan fakta sejarah yang diungkap secara mendetail, buku ini memberikan gambaran yang jelas tentang penderitaan yang dialami oleh orang-orang yang menjadi korban kekejaman PKI.', 'https://www.goodreads.com/book/show/55060807-banjir-darah?ref=nav_sb_ss_2_12'),

('50', 'Sejarah', 'Penghancuran PKI', 'Olle Tornquist', 'Komunitas Bambu', 'Oktober 2011', '979-3737-25-7', 'Buku Penghancuran PKI karya Olle Tornquist dengan pengantar dari budayawan Goenawan Mohamad merupakan sebuah karya yang menarik dan kontroversial. Dalam buku ini, Tornquist mengupas persoalan sejarah Peristiwa G30S 1965 dengan sudut pandang yang jarang diperhatikan secara serius sebelumnya. Melalui pertanyaan-pertanyaan tajam, seperti penyebab kegagalan PKI dan keterlibatan pemimpin PKI dalam peristiwa tersebut, buku ini mengajak pembaca untuk memahami lebih dalam bagaimana akhir riwayat partai tersebut belum banyak diteliti secara kritis. Dengan pengantar dari Goenawan Mohamad, buku ini menjadi sebuah sumbangan penting karena membahas PKI, partai komunis terbesar di luar Uni Soviet dan Republik Rakyat Cina, tanpa meninggalkan pemikiran yang progresif.', 'https://www.goodreads.com/book/show/12962696-penghancuran-pki?ref=nav_sb_ss_1_16'),

('51', 'Sejarah', 'Sejarah Peradaban Islam', 'Dr. Ahmadin', 'Kencana', 'Desember 2020', '978-623-218-589-0', 'Buku ini mempersembahkan sebuah perjalanan epik melalui sejarah panjang peradaban Islam, membongkar struktur sosial, spasial, dan spiritual masyarakat Arab pra-Islam hingga mengupas ketegangan kontradiktif Islam periode Mekkah dan Madinah. Sisi unik dan kompleks masa Khulafaur Rasyidin juga tampil menarik dengan perdebatan berat mengenai pemimpin penerus Nabi Muhammad saw. yang berakhir dengan terpilihnya Abu Bakar As-Siddiq sebagai khalifah pertama, menggambarkan kompleksitas pengambilan keputusan dalam umat Islam. Melalui telaah yang mendalam, buku menjelajahi perkembangan Islam dari Dinasti Umayyah dan Abbasiyah hingga masuknya Islam ke Eropa, Afrika, dan Asia Selatan, memberikan bahan refleksi yang memikat tentang dampak dan perjalanan peradaban Islam dalam skala global. Potret-potret yang ditampilkan dalam buku ini, meliputi puncak kejayaan serta perjuangan peradaban Islam, menjadi tonggak penting bagi pemahaman mendalam akan warisan sejarah dan keberadaban umat Muslim.', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=1344008'),

('52', 'Sejarah', 'Di Balik Runtuhnya Turki Utsmani', 'Deden A. Herdiansyah', 'Pro-U Media', 'Juni 2016', '978-602-7820-54-8', 'Dibalik Runtuhnya Turki Utsmani karya Deden A. Herdiansyah mengupas secara mendalam sejarah keruntuhan Kesultanan Turki Utsmani. Buku ini membawa pembaca pada serangkaian konspirasi dan intrik yang meruntuhkan kekhalifahan terakhir umat Islam ini. Deden menyajikan catatan sejarah yang runtut dan mengungkapkan peran musuh dari dalam dan luar yang menggerogoti Turki Utsmani hingga titik terlemahnya. Dengan gaya penulisan yang menarik, buku ini tidak hanya menarik bagi pencinta sejarah, tetapi juga membawa pemahaman mendalam akan perjalanan politik dan sosial yang mempengaruhi iman dan identitas umat Islam.', 'https://www.goodreads.com/book/show/34914767-di-balik-runtuhnya-turki-utsmani?ref=nav_sb_ss_1_32'),

('53', 'Sejarah', 'Atlas Wali Singo : buku pertama yang mengungkap Wali Songo sebagai fakta sejarah', 'Agus Sunyoto', 'Pustaka IIMaN', 'Juli 2014', '978-602-8648-09-7', 'Buku legendaris Atlas Wali Songo mengungkap secara mendalam keberadaan serta kontribusi para Wali Songo dalam menyebarkan Islam di Nusantara. Ditulis oleh sejarawan NU, KH Agus Sunyoto, buku ini memberikan gambaran yang kuat tentang eksistensi dan dakwah para Wali Songo, dengan menyoroti sejarah, keilmuan, dan budaya yang mereka warisi serta kembangkan. Melalui penjelasan yang jelas dan objektif, Agus Sunyoto berhasil membongkar mitos seputar identitas serta peran penting para Kanjeng Sunan, memperlihatkan bagaimana Islam dan budaya lokal mampu beriringan dalam kemasyarakatan yang seimbang.', 'https://opac.perpusnas.go.id/DetailOpac.aspx?id=878210'),

('54', 'Sejarah', 'Para Panglima Islam Penakluk dunia', 'Muhammad Ali', 'Ummul Qura', 'Juli 2016', '978-602-7637-51-1', 'Buku Para Panglima Penakluk Dunia karya Ustadz Muhammad Ali, mengulas perjalanan hidup para pahlawan Islam yang memukau. Kisah mereka, penuh dengan catatan penaklukan-penaklukan, menceritakan bagaimana dengan jihad dan iman, mereka berhasil menorehkan peradaban terbesar dan paling maju. Buku ini mengundang pembaca untuk menyelami kisah perjalanan jihad dan penaklukan para panglima Islam yang dengan keperwiraan, ketulusan, dan keikhlasan, berhasil menaklukan negeri-negeri yang dikuasai oleh orang-orang kafir penjajah. Sehingga, penduduk negeri-negeri tersebut mengalami perubahan yang luar biasa, dari sebelumnya memerangi dan membenci para prajurit Islam, menjadi prajurit-prajurit yang bergabung di bawah panji Islam hanya dalam waktu relatif singkat. Buku ini memberikan inspirasi keperwiraan, ketulusan, keikhlasan, dan pengorbanan bagi umat Islam, memotret peradaban sebagai hasil dari kehidupan penuh dengan kebaikan, ketentraman, keberkahan dan cahaya nan bersinar terang.', 'https://www.goodreads.com/book/show/34761761-para-panglima-islam-penakluk-dunia?from_search=true&from_srp=true&qid=dfaFrKHcdc&rank=1');

-- ada data yang harus dimasukan lagi??
